### ISSUE TITLE
file_relay_request_sources code error.

### ISSUE THREAD

**Issue by Vxer-Lee** [libimobiledevice-NET/imobiledevice-net#2]
I wonder why you want it to be zero.
![image](https://user-images.githubusercontent.com/27657137/211766258-0b43834a-4141-4488-8a1c-576a8db3c966.png)

![image](https://user-images.githubusercontent.com/27657137/211766662-99c940ca-8d8f-440e-a802-787ada56bb53.png)

**Comment by waynebonc** [comment]
Fixed.
